name: 'Docker setup'
description: 'docker-setup reusable steps'
inputs:
  docker-username:
    description: 'Docker hub username'
    required: true
  docker-password: 
    description: 'Docker hub password'
    required: true
runs:
  using: "composite"
  steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}